import 'OOp.dart';

var data = [
  {
    "id": 339,
    "day": "mercoledÃ¬ 24 aprile 2019",
    "dayShort": "24 aprile 2019",
    "hour": "08:00",
    "customer": {
      "id": 210,
      "name": "Silvano",
      "su	rname": "Conte",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Ponzano Veneto",
      "postalCode": "31050",
      "addressDetails": "",
      "phone": "3313237388",
      "address": "via Mattiazzo 3",
      "notes": ""
    },
    "service": "Installazione monosplit",
    "serviceId": 222,
    "duration": 250,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-04-24"
  },
  {
    "id": 340,
    "day": "lunedÃ¬ 29 aprile 2019",
    "dayShort": "29 aprile 2019",
    "hour": "08:00",
    "customer": {
      "id": 211,
      "name": "Ion",
      "surname": "Stepan",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Oderzo",
      "postalCode": "31046",
      "addressDetails": "",
      "phone": "3272430399",
      "address": "via Stadio 10",
      "notes": ""
    },
    "service": "Installazione monosplit",
    "serviceId": 222,
    "duration": 250,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-04-29"
  },
  {
    "id": 343,
    "day": "martedÃ¬ 30 aprile 2019",
    "dayShort": "30 aprile 2019",
    "hour": "13:10",
    "customer": {
      "id": 214,
      "name": "Pio",
      "surname": "Gelmetti",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Treviso",
      "postalCode": "31100",
      "addressDetails": "piano secondo",
      "phone": "3495751423",
      "address": "via Albona 3",
      "notes": ""
    },
    "service": "Installazione monosplit",
    "serviceId": 222,
    "duration": 250,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-04-30"
  },
  {
    "id": 384,
    "day": "giovedÃ¬ 02 maggio 2019",
    "dayShort": "02 maggio 2019",
    "hour": "08:10",
    "customer": {
      "id": 255,
      "name": "Giuliana",
      "surname": "Legovini",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Treviso",
      "postalCode": "31100",
      "addressDetails": "",
      "phone": "3489209001",
      "address": "piazza San Francesco 1/8",
      "notes": ""
    },
    "service": "sopralluogo zona 1",
    "serviceId": 220,
    "duration": 70,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-05-02"
  },
  {
    "id": 388,
    "day": "giovedÃ¬ 02 maggio 2019",
    "dayShort": "02 maggio 2019",
    "hour": "13:10",
    "customer": {
      "id": 259,
      "name": "Fulvia",
      "surname": "Berto",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Paese",
      "postalCode": "31038",
      "addressDetails": "",
      "phone": "3485621130",
      "address": "via Paolo IV 22",
      "notes": ""
    },
    "service": "sopralluogo zona 1",
    "serviceId": 220,
    "duration": 70,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-05-02"
  },
  {
    "id": 458,
    "day": "martedÃ¬ 07 maggio 2019",
    "dayShort": "07 maggio 2019",
    "hour": "10:40",
    "customer": {
      "id": 328,
      "name": "Giordana",
      "surname": "Grilli",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Treviso",
      "postalCode": "31100",
      "addressDetails": "",
      "phone": "3939941970",
      "address": "GIACOMO ZANELLA 8",
      "notes": ""
    },
    "service": "sopralluogo zona 1",
    "serviceId": 220,
    "duration": 70,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-05-07"
  },
  {
    "id": 2314,
    "day": "mercoledÃ¬ 11 settembre 2019",
    "dayShort": "11 settembre 2019",
    "hour": "08:00",
    "customer": {
      "id": 1498,
      "name": "Antonella ",
      "surname": "Toscano",
      "mail": "agendacondivisa.lmit@gmail.com",
      "city": "Treviso",
      "postalCode": "31100",
      "addressDetails": "",
      "phone": "3471999039",
      "address": "piazzetta filodrammatici 4",
      "notes": ""
    },
    "service": "sopralluogo zona 1",
    "serviceId": 220,
    "duration": 70,
    "color": "#3366cc",
    "status": "ACCETTATO",
    "store": "Treviso",
    "storeCode": "030",
    "teamName": "Squadra 1",
    "dateForApp": "2019-09-11"
  },
  {
    "id": 104273,
    "day": "martedÃ¬ 16 marzo 2021",
    "dayShort": "16 marzo 2021",
    "hour": "14:10",
    "customer": {
      "id": 68038,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "occupato\n",
    "serviceId": 0,
    "duration": 330,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-03-16"
  },
  {
    "id": 159561,
    "day": "martedÃ¬ 01 giugno 2021",
    "dayShort": "01 giugno 2021",
    "hour": "14:30",
    "customer": {
      "id": 105392,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "APPUNTAMENTO PRIVATO",
    "serviceId": 0,
    "duration": 330,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-01"
  },
  {
    "id": 159585,
    "day": "martedÃ¬ 08 giugno 2021",
    "dayShort": "08 giugno 2021",
    "hour": "14:00",
    "customer": {
      "id": 105407,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "APPUNTAMENTO PRIVATO",
    "serviceId": 0,
    "duration": 270,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-08"
  },
  {
    "id": 159584,
    "day": "giovedÃ¬ 10 giugno 2021",
    "dayShort": "10 giugno 2021",
    "hour": "14:00",
    "customer": {
      "id": 105406,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "APPUNTAMENTO PRIVATO",
    "serviceId": 0,
    "duration": 270,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-10"
  },
  {
    "id": 164622,
    "day": "martedÃ¬ 15 giugno 2021",
    "dayShort": "15 giugno 2021",
    "hour": "15:00",
    "customer": {
      "id": 108814,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "appuntamento PRIVATO",
    "serviceId": 0,
    "duration": 210,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-15"
  },
  {
    "id": 169894,
    "day": "giovedÃ¬ 17 giugno 2021",
    "dayShort": "17 giugno 2021",
    "hour": "17:30",
    "customer": {
      "id": 112302,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "SOPRALLUOGO PRECI LEKE",
    "serviceId": 0,
    "duration": 30,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-17"
  },
  {
    "id": 169861,
    "day": "martedÃ¬ 22 giugno 2021",
    "dayShort": "22 giugno 2021",
    "hour": "08:00",
    "customer": {
      "id": 112281,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "POSA CLIMA CREMASCO MATTIA",
    "serviceId": 0,
    "duration": 630,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-22"
  },
  {
    "id": 169830,
    "day": "giovedÃ¬ 24 giugno 2021",
    "dayShort": "24 giugno 2021",
    "hour": "14:00",
    "customer": {
      "id": 112257,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "SOPRALLUOGO MONSELLATO ORNELLA",
    "serviceId": 0,
    "duration": 30,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-24"
  },
  {
    "id": 169831,
    "day": "giovedÃ¬ 24 giugno 2021",
    "dayShort": "24 giugno 2021",
    "hour": "14:30",
    "customer": {
      "id": 112258,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "SOPRALLUOGO MICHELA BASSETTO ",
    "serviceId": 0,
    "duration": 30,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-24"
  },
  {
    "id": 169832,
    "day": "giovedÃ¬ 24 giugno 2021",
    "dayShort": "24 giugno 2021",
    "hour": "16:00",
    "customer": {
      "id": 112259,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "SOPRALLUOGO LUIGI CASANOVA",
    "serviceId": 0,
    "duration": 30,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-06-24"
  },
  {
    "id": 177128,
    "day": "giovedÃ¬ 01 luglio 2021",
    "dayShort": "01 luglio 2021",
    "hour": "14:00",
    "customer": {
      "id": 117270,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "appuntamento privato",
    "serviceId": 0,
    "duration": 270,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-07-01"
  },
  {
    "id": 176348,
    "day": "venerdÃ¬ 02 luglio 2021",
    "dayShort": "02 luglio 2021",
    "hour": "08:30",
    "customer": {
      "id": 116733,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "SOPRALLUOGO BURIOLA",
    "serviceId": 0,
    "duration": 30,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-07-02"
  },
  {
    "id": 176343,
    "day": "venerdÃ¬ 02 luglio 2021",
    "dayShort": "02 luglio 2021",
    "hour": "09:30",
    "customer": {
      "id": 116730,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "SOPRALLUOGO BURIOLA GIANLUCA",
    "serviceId": 0,
    "duration": 30,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-07-02"
  },
  {
    "id": 177129,
    "day": "giovedÃ¬ 15 luglio 2021",
    "dayShort": "15 luglio 2021",
    "hour": "14:00",
    "customer": {
      "id": 117271,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "appuntamento privato",
    "serviceId": 0,
    "duration": 270,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-07-15"
  },
  {
    "id": 177086,
    "day": "martedÃ¬ 27 luglio 2021",
    "dayShort": "27 luglio 2021",
    "hour": "14:20",
    "customer": {
      "id": 117240,
      "name": null,
      "surname": "",
      "mail": null,
      "city": "",
      "postalCode": "",
      "addressDetails": "",
      "phone": null,
      "address": "",
      "notes": ""
    },
    "service": "appuntamento privato",
    "serviceId": 0,
    "duration": 270,
    "color": "#999999",
    "status": "ACCETTATO",
    "store": "",
    "storeCode": null,
    "teamName": "Squadra 1",
    "dateForApp": "2021-07-27"
  }
];

void main() {
  // Shapes s1 = new Circle(7);
  // var circlearear = s1.CalculateArea();

  // print(circlearear);

  // Shapes s2 = Traingle(4, 5);
  // var trianglearear = s1.CalculateArea();
  // print(trianglearear);

  // Traingle t = Traingle(12, 23);
  // t.PrintMessage('Triangle');

  // TvRemoteController tv = TvRemoteController();
  // tv.increase();
  // print(tv.volume);

  // tv.decrease();
  // print(tv.volume);

  Order o = BurgerOrder();
  o.takeOrder();
  OrderPayment op = BurgerOrder();
  op.acceptpayment();
}
